name: root
dependencies:
- python=2.7.11
- pandas=0.18.1
- numpy=1.11.1
- scipy=0.18.1
- notebook
- scikit-learn
- matplotlib
- pip:
  - awscli==1.11.36
  - boto3==1.4.4
  - botocore==1.5.56
  - findspark==1.1.0
  - geojson==1.3.5
  - shapely==1.5.17.post1
